### ISSUE TITLE
The result of cartesian-product is scalar(string) instead of list

### ISSUE THREAD

**Issue by liuweichu** [geofffranks/spruce#153]
cartesian-product is pretty powerful for list comprehension.
However, it's result cannot be used as the input of `join` because the result of `cartesian-product` is actually a scalar.
This somehow conflicts with the semantics of `cartesian-product` because observed from the output, cartesian-product is a list.

Example:
http://play.spruce.cf/#79f90874d14afafbd8b7b218c7eb2dbd

**Comment by jhunt** [comment]
I suspect the issue is that type is fixed at merge time, and never updated by the operators at eval time, so while the _value_ of `$.ips_with_port` changes from a string (`(( cartesian-product ... ))`) to a list, it's recorded type doesn't get updated.

Probably ought to re-inspect values post-replacement so that they get properly updated to match reality.

Good catch!

**Comment by liuweichu** [comment]
Thanks for the quick reply.
Looking for the fix 😺
