### ISSUE TITLE
prune doesn't work when goes at the end (regression?)

### ISSUE THREAD

**Issue by giner** [geofffranks/spruce#158]
The following case worked with spruce v1.6.0 and does not work with v1.7.0:
```
$ cat test.yml 
test1: (( grab test2.test ))
test2: 
  test: t2
```
```
$ cat prune.yml 
test2: (( prune ))
```
```
$ spruce merge test.yml prune.yml 
1 error(s) detected:
 - $.test1: Unable to resolve `test2.test`: $.test2 is a scalar (not a map or a list)
```

At the same time it works if we move prune to the beginning:
```
$ spruce merge prune.yml test.yml 
test1: t2
```

**Comment by HeavyWombat** [comment]
I wrote an overhaul of the `(( prune ))` to fix issues with `(( inject ))`. This introduced the regression you found, because `(( prune ))` has a somehow special behavior in terms of being part of the structure while at the same time being _transparent_ or _non-existing_ during merge. I will provide a pull request shortly to fix this issue. Thanks for bringing it up.
