### ISSUE TITLE
Accept expression in key and not only on value part

### ISSUE THREAD

**Issue by itdove** [geofffranks/spruce#208]
We have a case where we need to have an expression on the key part instead of value part.

        group:
         - (( grab meta.key1 )):
              subgroup_info: (( grab meta.key2 )) 

The (( grab meta.key1 )) is rejected because not in the value part of the statement.
Do you have a solution or can implement a solution for that?

**Comment by alexparker215** [comment]
I have the same question. Can anyone shed some light on this issue?

**Comment by geofffranks** [comment]
Operators currently are only evaluated on values, not keys, which is why this does not work. I have a feeling trying to create a dependency tree for evaluation order when including keys as potential operators is going to be very difficult, as the paths to other operators may be changing over time due to the operations. I may be wrong though, so if you have a solution, feel free to submit a PR.

**Comment by geofffranks** [comment]
Closing as stale
