### ISSUE TITLE
spruce cannot merge 2 files, if one of them is empty and/or fully commented out

### ISSUE THREAD

**Issue by AlexeyUzhva** [geofffranks/spruce#256]
Test case:

1. File A.yml with empty contents an/or comments-only
2. File B.yml with YAML data

**Actual Result**: A.yml: Root of YAML document is not a hash/map: type assertion to map[interface]interface{} failed

**Expected Result**: A.yml will be handled as empty map.

This is important to handle, because if tool is used for merging different parts of config, it's generally valid scenario when one part will be commented out.

**Comment by HeavyWombat** [comment]
@AlexeyUzhva Could you share an example of your files? I suspect that your file `A.yml` is empty in the sense of not having any YAML data (just a comment). But that is not valid _empty_ YAML so to speak. Have a look at [my example on how an empty YAML would look](https://play.spruce.cf/#0f1cc9cf248f91601805d9b57194bded) like.

**Comment by geofffranks** [comment]
I was wondering if that was the case and the parser was just returning nil as the object, with no error. If so, we’d be able to convert it to an empty map before checking that at a map and merging

**Comment by prein** [comment]
@HeavyWombat Your example works as long as the empty YAML is on top. If you reverse the order, spruce will barf

**Comment by HeavyWombat** [comment]
@prein Interesting result. Thanks for brining that up. I will have a look at this if time permits. That shouldn't happen.

**Comment by prein** [comment]
@HeavyWombat thanks for looking into it and apologies for late reply. Pity I didn't include an example because now I'm not sure now what was the content of the files I was using for testing :\

For me the mandatory `{}` may be a bit problematic, in a case where yaml files are rendered from some other script prior to being handled with spruce.

**Comment by VasylTretiakov** [comment]
@HeavyWombat is right: spruce seems to properly handle empty, **but valid** YAML files. If the non-valid YAML file is supplied (e.g. an empty one), the error _Root of YAML document is not a hash/map: type assertion to map[interface]interface{} failed_ pops up.

**Comment by VasylTretiakov** [comment]
While the point of @HeavyWombat is clear (and it indeed works), I also find expectations of @AlexeyUzhva and @prein reasonable considering that _bosh-cli_ returns a newline in stdout for an empty _runtime-config_ (i.e. it does not return an empty map).
Could we just create an empty map in `cmd/spruce/main.go` _parseYAML_ function if the root of the merged file does not have one instead of exiting with error?
```
//before
return nil, ansi.Errorf("@R{Root of YAML document is not a hash/map}: %s\n", err.Error())
//after
ansi.Errorf("@R{Root of YAML document is not a hash/map, using empty map instead.}\n")
doc := make(map[interface{}]interface{})
```
