### ISSUE TITLE
Inconsistent Behavior when Parsing Json File

### ISSUE THREAD

**Issue by ywei2017** [geofffranks/spruce#258]
This seems to be an issue when the key is \d.\d. When there 2 or 1 digits, the (") is left in place.
```
me@home:  cat tmp.json
{
  "versions": {
    "4": "old",
    "4.4": "new",
    "4.4.4": "newer",
    "4.4.4.4": "newest"
  },
  "tags": {
    "v4": "old",
    "v4.b4": "new",
    "v4.b4.p4": "newer",
    "v4.b4.p4.c4": "newest"
  }
}

me@home : spruce merge < tmp.json
tags:
  v4: old
  v4.b4: new
  v4.b4.p4: newer
  v4.b4.p4.c4: newest
versions:
  "4": old
  "4.4": new
  4.4.4: newer
  4.4.4.4: newest

```

There should be no (") left behind when working correctly. Confirmed the issue at least 1.16.* and 1.17.*.

**Comment by ywei2017** [comment]
It is causing problems for me :-( 

What I posted is a trimmed down version of a bigger file, that I use to track which version of a product is installed in what environment.  The program gets confused since (4.4) in the example is considered absent, which is bad as ("4.4") should have translated to (4.4). 

I am thinking of doing some stupid "sed" on the yml file as workaround, but you know, that is stupid.

Thanks for the quick response..

**Comment by sorenh** [comment]
As far as I can tell, the first example you gave is correct. 4, 4.4, and 4.4.4 are all strings in your input file. 4.4.4 is not a valid int or float, so is treated like a string without any need for quotes. 4 and 4.4. without quotes would (correctly) be treated as an int and a float, respectively. To avoid that, they are quoted.

Are you by any chance trying to use the output with a tool that is not yaml aware? Otherwise, I'm unsure how it would cause problems.

The second example is a little trickier. JSON keys are always strings (whereas yaml allows any type as a key), so things can get lost in translation. We could either have a --super-strict option to simply refuse to JSONify yaml with any non-string keys. We could leave things as-is and issue a warning that there were duplicate keys and something got lost. At any rate, I thinkn this is a separate problem and warrants its own (Github) issue.

**Comment by sorenh** [comment]
Filed #259 about the lossy json conversion.

**Comment by ywei2017** [comment]
@geofffranks After letting the truth sink it that yaml keys are not always strings, I came to the realization that the issue I raised is not a valid one. So we can close this issue.

In the mean time, I think issues [259](https://github.com/geofffranks/spruce/issues/259) is valid and will help all use the tool in more precise ways.

Thanks all,
Yansheng
