### ISSUE TITLE
Concat string to array elements

### ISSUE THREAD

**Issue by CAFxX** [geofffranks/spruce#73]
We often have the need to append a certain string to all elements of an array. The primary use case is adding a port number to a list of IPs:
```
ips:
- 1.1.1.1
- 1.1.1.2
port: 8080
addr: (( ip ":" port ))
```
should produce
```
ips:
- 1.1.1.1
- 1.1.1.2
port: 8080
addr:
- 1.1.1.1:8080
- 1.1.1.2:8080
```

**Comment by filefrog** [comment]
What if `port` is a list too?

**Comment by geofffranks** [comment]
Additionally, what happens if they're lists of non-strings? such as lists of lists of strings.

In terms of implementation, it might be easier just to update the bosh-releases requiring things like this to take the list of one parameter and the other, and iterate over them when generating templates, when compared to the code that would need to go into spruce to support this, and guard against all of the edge cases.

**Comment by CAFxX** [comment]
> What if port is a list too?
I'd suggest "extend by modulo repetition" (i.e. if you have [A,B,C,D,E] and [1,2,3] you'd get [A1,B2,C3,D1,D2]) or throw an error.

> what happens if they're lists of non-strings? such as lists of lists of strings
Throw an error (I honestly can't see any good use-case for this)

> In terms of implementation, it might be easier just to update the bosh-releases requiring things like this 
This is exactly what I'm doing right now and it's a royal pain in the neck

**Comment by geofffranks** [comment]
I can see a good case being made for having it do a cartesian product of the lists as well. Was this something that you were able to do using spiff? If so, how did it work there?

**Comment by CAFxX** [comment]
AFAIK nor spiff nor spruce support this
