### ISSUE TITLE
Spruce is incorrectly producing an error

### ISSUE THREAD

**Issue by qanx** [geofffranks/spruce#76]
Recently encountered the following:

```
$ make refresh manifest
Refreshing global data for sandbox
Updated global data
Refreshing site data for sandbox
Updated site data
Building asv / sandbox
Working in /home/quinn/deployments/cloud-foundry-deployments/sandbox
1 error(s) detected:
 - $.jobs.3.templates.0: (( append )) operator not defined


make: *** [manifest] Error 2

$ cd ../

$ grep -R "append" *
sandbox/.site/jobs.yml:  - (( append ))
site/jobs.yml:  - (( append ))

$ less site/jobs.yml

$ spruce -v
spruce - Version 0.12.0 (master)
```

The lines in question are:

```
 72   templates:
 73   - (( append ))
 74   - name: shield-agent
 75     release: shield
```

**Comment by alext** [comment]
I'm seeing this with latest master as well.  Given the following files:

`a.yml`:
```yaml
a:
  - foo
  - bar
  - baz
```
`b.yml`:
```yaml
a:
  - (( append ))
  - qux
```

`spiff merge a.yml b.yml` returns the error:
```
1 error(s) detected:
 - $.a.0: (( append )) operator not defined
```

**Comment by alext** [comment]
I've seen this error if the array in question has not been defined in a previous file (ie the first occurrance of `templates` cannot use `append` or any other operator...)

**Comment by filefrog** [comment]
I think @alext hit on the root cause.

Consider: http://play.spruce.cf/#14d398e596f40761e427

If you change the list2 / list3 keys to be 'list', it Just Works (TM)

Solution is probably to go through all of the arrays during the Merge phase and look for (( ... )) initial elements and throw errors, or, we could define a operators for `(( prepend ))`, `(( append ))`, etc. that throw the errors.

I think I like the latter better.
